### ISSUE TITLE
version requirements are pretty strict

### ISSUE THREAD

**Issue by gmabey** [markvincze/sabledocs#17]
Hello,

It looks to me like the version requirements you impose:
```
Jinja2==3.1.2
Markdown==3.4.1
protobuf==4.21.6
lunr==0.6.2
```
are pretty strict, in that they only allow for a single version to be used instead of a >= range.  Also, are you convinced that it will only run on python 3.11 or should 3.10 work?

I ask because I try to use `fpm` https://github.com/jordansissel/fpm to generate `.deb` files of pypi packages as an alternative installation method, and that isn't working out for me very well just yet.

**Comment by markvincze** [comment]
Hi @gmabey,
Thanks for the comment!
This is the first Python package I maintain, so I wasn't sure what the usual pattern is.
Is it more typical to specify package ranges? I guess I could change all of these to enforce only the major version.

For the Python version, there is one specific reason for needing at least 3.11, and that's the usage of `tomllib`, because that was added to the base library in 3.11.
