### ISSUE TITLE
hidden-packages not doing what I expected

### ISSUE THREAD

**Issue by ctuffli** [markvincze/sabledocs#65]
Running `sabledocs` generates a list of the Packages on the `index.html` page including packages (i.e., `buf.validate`) in the `hidden-packages` list.

```shell
(.venv) $ cat sabledocs.toml
module-title = "Service Documentation"
output-dir = "docs"

footer-content = "© 2024 Big Corp. All rights reserved."

hidden-packages = ["buf.validate","buf.validate.priv"]
```
From the description in the comment, I was expecting packages listed in "hidden" to not appear on the index page. Did I misunderstand what this option does? Is the syntax for the `hidden-packages` incorrect?

**Comment by markvincze** [comment]
Hi @ctuffli,

Thanks for reporting this issue!
You're right, when this feature was introduced, only the logic was implemented to have the `non_hidden_packages` field being available and correctly populated in the data model, but the default HTML template was not changed to start using it. (It could've been used from a custom template though.)
I changed the template now in #66, and it was released in version `0.13.770`, can you give it a try?

**Comment by ctuffli** [comment]
Thanks for the fix! This does remove the packages from `index.html`, but curiously, sabledocs still generates the html documents for hidden packages and adds those to `search.html`

**Comment by markvincze** [comment]
@ctuffli thanks for testing!
Indeed the change I implemented was a bit naïve, the file generation and the search index was not taken into account. Plus there was one more issue: the type name links were generated for types in hidden packages as well, so you could end up on the page of a hidden package by clicking on the type name too.
I fixed these issues in #67, and it's released in version 0.13.784, hopefully now it works correctly. If you can give it a try, that'd be appreciated!

**Comment by ctuffli** [comment]
Yup, the latest works great in our testing. Thank you for fixing this!

**Comment by veqryn** [comment]
@markvincze I think this may need to be re-opened or I don't understand the field either.
I have this in my toml:
`hidden-packages = ["google.api", "google.protobuf", "grpc.gateway.protoc_gen_openapiv2.options"]`

However, the `index.html` that gets generated still lists these 3 packages.
I thought the point of this field was to hide them on the index (while still generating them)?

**Comment by markvincze** [comment]
Hi @veqryn,

Thanks for the patience on this one!

Indeed that's how it's supposed to work, so if it's not working like that, that's a bug.
Can you check which version of the package you're using? Because it was only changed in a recent version to use `non_hidden_packages` in the default template, prior to that this could only be used with a custom template.

And could you test it with the project in the `sample` folder?
I tested it now by running `sabledocs` in the `sample` folder, and opening the generated docs, and both packages in the proto are rendered:

![image](https://github.com/user-attachments/assets/fcb44968-7038-4898-90ae-e1855912c8e8)

Then if I add this line to the `sabledocs.toml`:

```
hidden-packages = [ "google.pubsub.v1" ]
```

And generated the docs again, then the `google.pubsub.v1` package is not rendered in the index:

![image](https://github.com/user-attachments/assets/2a46073c-d72a-4f30-bead-d741d257848a)

Could you do the same test to see if it works like this for you as well? If not, then could you verify which version of the `sabledocs` package are you running?

**Comment by veqryn** [comment]
Ok, i think the problem might actually be the latest versions you've created of sabledocs want an older version of grpc/protobuf, while older versions of sabledocs are fine with newer versions of grpc/protobufs.

**Comment by veqryn** [comment]
Created a new issue here: https://github.com/markvincze/sabledocs/issues/78

**Comment by veqryn** [comment]
@markvincze now that I am on the latest version, I am wondering what the expected behavior should be for hidden packages?
So for example, I am hiding `["google.api", "google.protobuf", "grpc.gateway.protoc_gen_openapiv2.options"]`
I assumed that meant those package roots would be hidden on the landing page, but that if someone clicked a link to `google.protobuf.Timestamp` it would still be visible?
It seems those links don't exist anymore.
